import React, { useState } from 'react';
import { CalculatorState } from '../types';
import { Calculator, DollarSign, Users, PieChart, ShieldCheck, Info, Check, Copy, TrendingUp, Cpu, Scale, Building2, HeartPulse, Lock } from 'lucide-react';

export const EconomicCalculator: React.FC = () => {
  const [calc, setCalc] = useState<CalculatorState>({
    populationMillions: 160,
    participationPercent: 10,
    monthlyContributionUSD: 50
  });

  const [copied, setCopied] = useState(false);

  // Calculations
  const activeContributors = Math.round(calc.populationMillions * 1000000 * (calc.participationPercent / 100));
  const monthlyPool = activeContributors * calc.monthlyContributionUSD;
  const annualPool = monthlyPool * 12;
  const fiveYearPool = annualPool * 5;

  const fmtCurrency = (val: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0
    }).format(val);
  };

  const fmtCompact = (val: number) => {
    if (val >= 1e9) return `$${(val / 1e9).toFixed(2)} Billion`;
    if (val >= 1e6) return `$${(val / 1e6).toFixed(1)} Million`;
    return fmtCurrency(val);
  };

  const setPreset = (pop: number, part: number, monthly: number) => {
    setCalc({
      populationMillions: pop,
      participationPercent: part,
      monthlyContributionUSD: monthly
    });
  };

  const handleCopy = () => {
    const summary = `THE 56TH STAR INITIATIVE - ECONOMIC SCENARIO SUMMARY
• Population Base: ${calc.populationMillions}M Sixth Region Members
• Participation Rate: ${calc.participationPercent}% (${(activeContributors / 1e6).toFixed(2)}M Active Contributors)
• Monthly Contribution: $${calc.monthlyContributionUSD}/month
• Monthly Sovereign Pool: ${fmtCurrency(monthlyPool)}
• Annual Sovereign Pool: ${fmtCurrency(annualPool)}
• 5-Year Cumulative Pool: ${fmtCurrency(fiveYearPool)}
*Research model scenario only; not a tax or investment solicitation.`;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const allocationCategories = [
    {
      label: 'Sovereign STEM, Tech & AI Education Endowments',
      percent: 30,
      icon: <Cpu className="w-4 h-4 text-emerald-400" />,
      color: 'bg-emerald-500',
      description: 'Funding research labs, university scholarships, AI compute hubs, and youth tech academies across the diaspora and Africa.'
    },
    {
      label: 'Legal Defense, Land & Sovereign Rights Vaults',
      percent: 25,
      icon: <Scale className="w-4 h-4 text-amber-400" />,
      color: 'bg-amber-500',
      description: 'Supporting international legal advocacy, human rights defense, territorial restitution studies, and treaty drafting.'
    },
    {
      label: 'Pan-African Trade & Logistics Infrastructure',
      percent: 20,
      icon: <Building2 className="w-4 h-4 text-[#d8aa28]" />,
      color: 'bg-[#d8aa28]',
      description: 'Investing in diaspora-owned shipping lanes, trade guarantee funds, ports, energy grids, and digital payment rails.'
    },
    {
      label: 'Health Autonomy, Agriculture & Food Security',
      percent: 15,
      icon: <HeartPulse className="w-4 h-4 text-rose-400" />,
      color: 'bg-rose-500',
      description: 'Building regional pharmaceutical manufacturing, sustainable agriculture, clean water projects, and medical research.'
    },
    {
      label: 'Shūrā Assemblies & TTL Cryptographic Infrastructure',
      percent: 10,
      icon: <Lock className="w-4 h-4 text-sky-400" />,
      color: 'bg-sky-500',
      description: 'Maintaining zero-knowledge consultation platforms, open audit ledgers, regional assemblies, and constituent outreach.'
    }
  ];

  return (
    <div className="bg-[#0b1b14] border border-[#1e3b2e] rounded-2xl p-6 sm:p-8 space-y-8 text-slate-100 shadow-xl">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#1d382c] pb-6">
        <div>
          <div className="flex items-center gap-2 text-[#f1ca54] font-mono text-xs font-bold uppercase tracking-wider mb-1">
            <Calculator className="w-4 h-4 text-[#d8aa28]" />
            <span>Sixth Region Economic Capacity Model</span>
          </div>
          <h2 className="font-serif text-2xl sm:text-3xl font-bold text-white">
            Participation Scenario Calculator
          </h2>
          <p className="text-sm text-slate-300 mt-1">
            Model the self-determination financial pool generated by voluntary civic contributions across the Sixth Region.
          </p>
        </div>

        {/* Preset Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => setPreset(160, 2, 25)}
            className="text-xs bg-[#12281e] hover:bg-[#1b382a] border border-[#234534] px-3 py-1.5 rounded-lg text-slate-300 transition-colors"
          >
            Modest (2%)
          </button>
          <button
            onClick={() => setPreset(160, 10, 50)}
            className="text-xs bg-[#183527] hover:bg-[#204533] border border-[#d8aa28]/40 text-[#f1ca54] px-3 py-1.5 rounded-lg font-semibold transition-colors"
          >
            Target (10%)
          </button>
          <button
            onClick={() => setPreset(160, 25, 100)}
            className="text-xs bg-[#12281e] hover:bg-[#1b382a] border border-[#234534] px-3 py-1.5 rounded-lg text-slate-300 transition-colors"
          >
            High Civic (25%)
          </button>
        </div>
      </div>

      {/* Calculator Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Controls Column */}
        <div className="lg:col-span-6 space-y-6 bg-[#07130e] p-6 rounded-xl border border-[#1a3328]">
          <h3 className="font-serif text-lg font-bold text-white flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-[#d8aa28]" />
            Scenario Variable Inputs
          </h3>

          {/* Variable 1: Population */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <label className="text-slate-300 font-medium">
                Sixth Region Diaspora Base
              </label>
              <span className="font-mono text-[#f1ca54] font-bold">
                {calc.populationMillions} Million People
              </span>
            </div>
            <input
              type="range"
              min="50"
              max="250"
              step="5"
              value={calc.populationMillions}
              onChange={(e) => setCalc({ ...calc, populationMillions: Number(e.target.value) })}
              className="w-full accent-[#d8aa28] bg-[#14281f] h-2 rounded-lg cursor-pointer"
            />
            <div className="flex justify-between text-[11px] text-slate-500 font-mono">
              <span>50M (Core Urban)</span>
              <span>160M (AU Estimate)</span>
              <span>250M (Broad Diaspora)</span>
            </div>
          </div>

          {/* Variable 2: Participation Rate */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <label className="text-slate-300 font-medium">
                Active Participation Rate
              </label>
              <span className="font-mono text-[#f1ca54] font-bold">
                {calc.participationPercent}% ({((calc.populationMillions * calc.participationPercent) / 100).toFixed(1)}M Contributors)
              </span>
            </div>
            <input
              type="range"
              min="1"
              max="50"
              step="1"
              value={calc.participationPercent}
              onChange={(e) => setCalc({ ...calc, participationPercent: Number(e.target.value) })}
              className="w-full accent-[#d8aa28] bg-[#14281f] h-2 rounded-lg cursor-pointer"
            />
            <div className="flex justify-between text-[11px] text-slate-500 font-mono">
              <span>1% (Pilot Group)</span>
              <span>10% (Target Shūrā)</span>
              <span>50% (National Scale)</span>
            </div>
          </div>

          {/* Variable 3: Monthly Contribution */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <label className="text-slate-300 font-medium">
                Monthly Voluntary Civic Contribution
              </label>
              <span className="font-mono text-[#f1ca54] font-bold">
                ${calc.monthlyContributionUSD} / month (${calc.monthlyContributionUSD * 12}/yr)
              </span>
            </div>
            <input
              type="range"
              min="5"
              max="200"
              step="5"
              value={calc.monthlyContributionUSD}
              onChange={(e) => setCalc({ ...calc, monthlyContributionUSD: Number(e.target.value) })}
              className="w-full accent-[#d8aa28] bg-[#14281f] h-2 rounded-lg cursor-pointer"
            />
            <div className="flex justify-between text-[11px] text-slate-500 font-mono">
              <span>$5 (Micro-pledge)</span>
              <span>$50 (Standard)</span>
              <span>$200 (Patron Level)</span>
            </div>
          </div>

          {/* Actuarial Note */}
          <div className="bg-[#0e2118] border border-[#1b3b2c] p-3.5 rounded-lg text-xs text-slate-400 space-y-1">
            <div className="flex items-center gap-1.5 text-[#f1ca54] font-semibold">
              <Info className="w-3.5 h-3.5" />
              <span>Actuarial Model Note</span>
            </div>
            <p className="leading-relaxed">
              This model demonstrates that even micro-contributions across a fraction of the diaspora generate self-funding capital dwarfing traditional foreign development aid.
            </p>
          </div>
        </div>

        {/* Results Column */}
        <div className="lg:col-span-6 space-y-6">
          {/* Big Output Cards */}
          <div className="bg-gradient-to-br from-[#0c261a] to-[#071710] border border-[#d8aa28]/30 rounded-xl p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between border-b border-[#1c3c2e] pb-3">
              <span className="text-xs font-mono uppercase text-[#d8aa28] font-bold tracking-wider">
                Annual Sovereign Development Pool
              </span>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-xs text-slate-300 hover:text-white bg-[#152e22] hover:bg-[#1f4231] px-2.5 py-1 rounded border border-[#274f3b] transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
                <span>{copied ? 'Copied' : 'Copy Scenario'}</span>
              </button>
            </div>

            <div className="space-y-1">
              <div className="text-3xl sm:text-4xl lg:text-5xl font-serif font-extrabold text-[#f1ca54] tracking-tight">
                {fmtCurrency(annualPool)}
              </div>
              <p className="text-xs text-slate-400 font-mono">
                Generated per year from {(activeContributors / 1e6).toFixed(2)} million voluntary participants.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-3 pt-3 border-t border-[#1c3c2e]">
              <div className="bg-[#081811] p-3 rounded-lg border border-[#183326]">
                <span className="text-[11px] text-slate-400 block font-mono">Monthly Pool</span>
                <span className="text-lg font-bold text-white font-mono">{fmtCompact(monthlyPool)}</span>
              </div>
              <div className="bg-[#081811] p-3 rounded-lg border border-[#183326]">
                <span className="text-[11px] text-slate-400 block font-mono">5-Year Cumulative</span>
                <span className="text-lg font-bold text-[#f1ca54] font-mono">{fmtCompact(fiveYearPool)}</span>
              </div>
            </div>
          </div>

          {/* Allocation Breakdown */}
          <div className="bg-[#07130e] p-6 rounded-xl border border-[#1a3328] space-y-4">
            <h4 className="font-serif text-base font-bold text-white flex items-center justify-between">
              <span className="flex items-center gap-2">
                <PieChart className="w-4 h-4 text-[#d8aa28]" />
                Proposed Sovereign Fund Allocation
              </span>
              <span className="text-xs font-mono text-[#f1ca54]">100% Total</span>
            </h4>

            <div className="space-y-3.5">
              {allocationCategories.map((cat, idx) => {
                const catAmount = (annualPool * cat.percent) / 100;
                return (
                  <div key={idx} className="space-y-1.5">
                    <div className="flex items-center justify-between text-xs font-medium">
                      <span className="flex items-center gap-2 text-slate-200">
                        {cat.icon}
                        <span>{cat.label}</span>
                      </span>
                      <span className="font-mono text-[#f1ca54] font-bold shrink-0">
                        {fmtCompact(catAmount)} ({cat.percent}%)
                      </span>
                    </div>
                    {/* Progress Bar */}
                    <div className="w-full bg-[#13281f] h-2 rounded-full overflow-hidden">
                      <div
                        className={`h-full ${cat.color} transition-all duration-300`}
                        style={{ width: `${cat.percent}%` }}
                      />
                    </div>
                    <p className="text-[11px] text-slate-400 leading-snug">
                      {cat.description}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
